### ISSUE TITLE
TabCompleter not work

### ISSUE THREAD

**Issue by yungzinqpaye** [cloudnode-pro/CloudnodeMSG#54]
hello, i have a problem, tabcompleter does not work for normal players, to issue rights i use luckperms, right i issued “cloudnodemsg.use”. For OP players everything works, for default group it doesn't work. Messages are sent, just not displaying nicknames
![image](https://github.com/user-attachments/assets/3ef5c1a2-b5a8-4a07-9f8d-8c574612c70a)

**Comment by yungzinqpaye** [comment]
I use purpur-1.21-2284, I mean that normal players write /msg and they do not see the nicknames of the players who are online, but people with OP is displayed
In the screenshot I gave an example of how it is displayed in players with OP
![image](https://github.com/user-attachments/assets/c0971c45-4323-48e3-b8e6-fc600d79bfed)

**Comment by zefir-git** [comment]
I couldn't reproduce this issue. Do you have `commands: suggest-player-names-when-null-tab-completions` set to true in `config/paper-global.yml`?

**Comment by yungzinqpaye** [comment]
thanks bro, it works!
